## Hotel Configuration
hotel.name=Have

## Database Configuration
database.host=127.0.0.1
database.port=3306
database.user=root
database.psw=cosimo
database.source=cosmic

## Game Configuration
game.tcp.ip=127.0.0.1
game.tcp.port_nitro=2096
game.tcp.port_flash=3000
game.tcp.packets_log=false